spring:
  application:
    name: clazzprovider
  cloud:
    config:
      discovery:
        enable: true
      serviceId: register-server
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/school
    username: zhangxuli
    password: root
server:
  port: 8706

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka
  instance:
    prefer-ip-address: true
    hostname: ${spring.cloud.client.ip-address}
    instance-id: http://${spring.cloud.client.ip-address}:${server.port}
mybatis:
  type-aliases-package: com.ali.pojo
  mapper-locations: classpath:mapper/*Dao.xml
